pmem/syscall_intercept

src/intercept_util.c
It doesn't exist in kernel interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/19)
=> Remove flags argument from faccessat logger.

src/intercept.h, src/intercept_desc.c
See: #5
"magic number - pls, comment on why it's 0x10"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/21)
=> Some explanation about struct section_list

README.md
See: #5
Document in Readme.md what each dependancy is used for.
"perl -- for checking code style errors (or something similar)"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/22)
=> Add comment about perl in README.md

test/CMakeLists.txt, test/check_log.cmake
It is too hard to predict what is going to end up in the logs
with ASAN, gcov, etc...
The logs are still checked while doing tests without EXPECT_SPURIOUS_SYSCALLS, so this should not be a problem. I gave up on matching logs after this build: https://travis-ci.org/GBuella/syscall_intercept/jobs/249368556
Ref: #7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/32)
=> Skip log matching when EXPECT_SPURIOUS_SYSCALLS=ON

src/intercept_template.s
This is expected to make stack unwinding by debuggers more reliable.
See commit messages for more explanation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/37)
=> intercept asm template improvements/fixes

utils/docker/build.sh
The build runs with uid 1000 inside docker.
The Precise travis image happens to use this uid for checking
out the sources, but the Trusty travis images uses uid 2000.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/43)
=> docker: chmod repo

src/intercept_util.c
We were printing 2nd argument twice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/45)
=> Fix decoding of fcntl syscall.

CMakeLists.txt
In intermediary target to fix parallel builds. Two
targets depend on syscall_intercept_scoped.o, and apparently
in parallel builds CMake often executed the commands twice, which
sometimes resulted in a failing builds.
An example of such build failure:
```
[ 83%] Built target syscall_intercept_unscoped
[ 83%] Hiding symbols
[ 84%] Hiding symbols
/usr/bin/objcopy: error: the input file 'syscall_intercept_scoped.o' is empty
CMakeFiles/syscall_intercept_static.dir/build.make:61: recipe for target 'syscall_intercept_scoped.o' failed
make[2]: *** [syscall_intercept_scoped.o] Error 1
```
Adding a custom_target hopefully makes things better.
See also:
https://cmake.org/Bug/view.php?id=10082
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> CMake: add target generate_syscall_intercept_scoped

.travis.yml, README.md, utils/docker/images/Dockerfile.ubuntu-16.04, utils/docker/images/build-pmemfile.sh
And a few other superfluous modifications under utils/docker, to trigger
a docker image rebuild.
The travis build on master was meant to trigger docker image pushing once #51 was merged, but actually did not happen (despite the misleading fact that the corresponding travis build is green): 
```
The command "./build.sh" exited with 0.
$ if [[ $PUSH_THE_IMAGE -eq 1 ]]; then images/push-image.sh $OS:$OS_VER; fi
ERROR: wrong argument.
Usage:
push-image.sh <OS-VER>
where <OS-VER>, for example, can be 'ubuntu-16.04', provided  a Docker image tagged with pmem/syscall_intercept:ubuntu-16.04 exists locally.
Done. Your build exited with 0.
```
Almost there!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Fix a typo in travis yml

test/CMakeLists.txt, test/libcintercept2.log.match, test/prog_using_vfork.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/50)
Ref: #3
=> Add test using vfork

utils/docker/build.sh, utils/docker/pull-or-rebuild-image.sh
Coverity job has not been configured properly - there was no cron job for syscall_intercept on Travis, so Coverity analysis was never performed (probably with an exception of initial build). When I enabled it, job failed because of empty COVERITY_SCAN_PROJECT_NAME variable (initialized by PROJECT).
This PR fixes that and speeds up Coverity integration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/56)
=> Coverity integration fix + optimization

.travis.yml
Without that people who fork syscall_intercept have to set those values
in theirs Travis configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/57)
=> Provide default values of GITHUB_REPO and DOCKERHUB_REPO.

CMakeLists.txt, cmake/find_capstone.cmake
* The path to the directory containing capstone's library
provided by capstone's package config file was ignored.
* Attempting to find capstone is done before checking for toolchain
features, as that is more likely to fail than the other checks, and this
way the user is notified earlier.
* More verbose error message when capstone is not found.
I cloned capstone from github, installed it (not in a default path), and noticed that syscall_intercept ignored the `-L` flag from capstone's .pc file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/61)
=> Improve capstone finding code

test/pattern_loop.in.s, test/pattern_loop.out.s, test/pattern_loop2.in.s, test/pattern_loop2.out.s, test/pattern_nop_padding1.out.s, test/pattern_nop_padding2.out.s, test/pattern_nop_padding3.out.s
The "jmp 0b" "jmp 0f" syntax to jump backward, or forward to
numbered labels doesn't seem to be available in intel syntax
mode when using clang 5, or clang 6.
Fixes #63
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/64)
=> Fix label usage in test asm patterns

test/libcintercept0.log.match, test/libcintercept0_child.log.match
Some libc implementations might translate an `open` libc call to an `openat` syscall.
arch-linux glibc-2.26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/68)
=> Fix expected form of open in test

cmake/find_capstone.cmake
The message about not finding capstone could be confusing,
when pkg-config is not installed, but libcapstone is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/74)
=> Mention pkg-config when capstone is not found

test/libcintercept0.log.match
The wait4 syscall didn't match (Ubuntu 18.04, glibc 2.27)
```
25: /home/tej/code/syscall_intercept/test/libcintercept0.log.match:5   $(S) $(XX) -- wait4(-1, 0x0, 0x0, 0x0) = ?
25: .log.logging:3         /lib/x86_64-linux-gnu/libc.so.6 0xe45ef -- wait4(4294967295, 0x0, 0x0, 0x0) = ?
25: FAIL: match.pl: /home/tej/code/syscall_intercept/test/libcintercept0.log.match:5 did not match pattern
```
=> test: minor fix in test/libcintercept0.log.match

src/intercept.c
errno digits must be converted to ASCII when rendering error code for
display.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/95)
=> Fix error_code display on error

CMakeLists.txt
C++ compiler is only used for checking if the interface header file can be compiled as C++.
This doesn't need to block a build when on a new box one forgets to install a C++ compiler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/100)
=> CMake: make C++ usage optional

.travis.yml, src/disasm_wrapper.c, src/disasm_wrapper.h, src/intercept.c, src/intercept.h, src/intercept_util.c, src/intercept_util.h, src/patcher.c, test/CMakeLists.txt, test/asm_pattern.c, test/pattern_endbr64.in.S, test/pattern_endbr64.out.S, test/pattern_lea_rip_r12.in.S, test/pattern_lea_rip_r12.out.S, test/pattern_lea_rip_rdi.in.S, test/pattern_lea_rip_rdi.out.S, travis_prepare_docker.sh, travis_simple_build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/98)
=> Add code handling endbr64 and RIP relative lea instructions

src/intercept.h
Fixes compilation with GCC 10. (multiple definition of cmdline)
Note that "Test #43: syscall_format_logging" (`make test`) fails in both cases, without this change compiled by clang as well as with this change compiled by gcc, therefore probably unrelated. I didn't do any further testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/107)
=> Mark global variable as extern

src/intercept.c, test/hook_test_clone_preload.c, test/test_clone_thread_preload.c
glibc has been using clone3 internally since
commit d8ea0d0168b190bdf138a20358293c939509367f.
=> Fix clone3 crash in glibc 2.34+
