doc/generated/libsyscall_intercept.3
doc/libsyscall_intercept.3.md
examples/CMakeLists.txt
examples/fork_ban.c
include/libsyscall_intercept_hook_point.h
src/intercept.c
src/intercept.h
src/intercept_template.s
src/intercept_util.c
src/patcher.c
test/CMakeLists.txt
test/asm_pattern.c
test/hook_test_clone_preload.c
test/libcintercept0.log.match
test/test_clone_thread.c
test/test_clone_thread_preload.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/2)

Handling fork/clone

---

.travis.yml
README.md
utils/docker/build.sh
utils/docker/pull-or-rebuild-image.sh
utils/docker/run-coverity.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/13)

Integrate Coverity

---

src/disasm_wrapper.c
src/intercept.c
src/intercept.h
src/intercept_desc.c
src/intercept_util.c
src/patcher.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/14)

Fix typos in comments.

---

src/patcher.c

Generated assembly is exactly the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/15)

Use more idiomatic code for extracting bytes.

---

.travis.yml
CMakeLists.txt
codecov.yml
test/CMakeLists.txt
test/hook_test.c
test/hook_test_data.h
test/hook_test_preload.c
test/libcintercept1.log.match
utils/docker/build.sh
utils/docker/run-coverage.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/18)

Integrate codecov.io

---

src/intercept.c
src/intercept_util.c
src/intercept_util.h

To achieve piece with coverity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/23)

Remove intercept_logs routine

---

src/intercept_util.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/24)

Decode more syscalls.

---

.travis.yml
utils/docker/build.sh
utils/docker/run-build.sh

#25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/26)

utils: add support for CXX to docker scripts

---

test/intercept_sys_write.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/27)

expect spurious syscalls in intercept_sys_write

---

src/disasm_wrapper.c
test/CMakeLists.txt
test/pattern3.in.s
test/pattern3.out.s
test/pattern4.in.s
test/pattern4.out.s

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/29)

Recognize call in text

---

utils/match.pl

Copy from NVML tree.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/30)

Update match script

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/31)

Add CodeCov and Travis badges.

---

src/intercept.h
src/intercept_desc.c
test/CMakeLists.txt
test/pattern_symbol_boundary3.in.s
test/pattern_symbol_boundary3.out.s

For explanation, see the commit messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/33)

Remove skip ranges

---

src/intercept.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/34)

more verbose logging in should_patch_object

---

examples/CMakeLists.txt
examples/syscall_desc.c
examples/syscall_desc.h
examples/syscall_logger.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/35)

Add syscall logging example

---

src/intercept_util.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/36)

Fix decoding of getcwd syscall.

---

examples/syscall_desc.c
examples/syscall_desc.h
examples/syscall_logger.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/38)

Logging continued

---

doc/generated/libsyscall_intercept.3
doc/libsyscall_intercept.3.md
examples/syscall_logger.c
include/libsyscall_intercept_hook_point.h
src/entry.c
src/intercept.c
src/intercept.h
src/intercept_desc.c
src/intercept_util.c
src/patcher.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/40)

Fixes related to calling syscall_no_intercept

---

utils/cstyle.pl

Copy the cstyle script from NVML.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/42)

cstyle -- sync with NVML/cstyle

---

utils/docker/images/Dockerfile.fedora-25
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/build-image.sh
utils/docker/images/build-pmemfile.sh
utils/docker/images/install-nvml.sh

This uses cmake options not in pmemfile yet, see:
https://github.com/pmem/pmemfile/pull/339
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/48)

Use pmemfile in travis tests

---

.travis.yml
README.md
utils/docker/build.sh
utils/docker/images/build-image.sh
utils/docker/images/push-image.sh
utils/docker/prepare-environment.sh
utils/docker/pull-or-rebuild-image.sh
utils/docker/run-build-package.sh
utils/docker/run-build.sh
utils/docker/run-coverity.sh

The docker user, repo, github repo are no longer hardwired in
the scripts, they are expected to be provided by a travis environment.
Most of these changes are based on the docker related scripts in the pmemfile repo:
https://github.com/pmem/pmemfile/tree/master/utils/docker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/51)

Revamp docker machinery

---

src/intercept_util.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/53)

Fix (f)chmod logging

---

codecov.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/54)

Disable reporting of coverage for tests.

---

src/intercept_util.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/59)

Syscall logging improvements.

---

examples/syscall_logger.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/60)

logging example -- fix a typo in a condition

---

.travis.yml
CMakeLists.txt
cmake/find_capstone.cmake
utils/docker/build.sh
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/build-capstone.sh
utils/docker/run-build.sh

This PR builds on #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/62)

Test with capstone's experimental branch

---

src/intercept_util.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/65)

Improve logging of pipe/pipe2.

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/66)

Add gen_ctags target

---

src/intercept_log.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/70)

Fix typos in intercept_log.c

---

src/syscall_formats.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/69)

Fix symlinkat format

---

src/intercept_desc.c

The path opened by this function was:
`"/proc/sys/vm/mmap_min_addr,"`
Which of course always failed, due to the comma at the end
of the string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/73)

Fix get_min_address function

---

debian/control

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/75)

Add missing build depends to Debian control file

---

debian/control
src/syscall_formats.c
test/syscall_format.c

Hey, I have a few fixes to build against old Debian Jessie. The last commit of this series is *maybe/probably* not the right thing, it fixes the build, but maybe it breaks the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/76)

Fixes to build against Debian Jessie

---

utils/docker/run-coverity.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/82)

common: fix Coverity patch path

---

src/intercept_util.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/86)

Typo: Uknown -> Unknown

---

test/CMakeLists.txt
utils/check_license/check-headers.sh
utils/check_license/check-license.c
utils/check_license/file-exceptions.sh

Should supersede #87 and #94.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/96)

common: update check-license from pmdk

---

src/intercept.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/syscall_intercept/99)

Remove some dead code

---

CMakeLists.txt

This option is disabled by default.

Add option to statically link capstone
